### ISSUE TITLE
[Bug]: Does not work with rules_js 2.0 RC

### ISSUE THREAD

**Issue by matthewjh** [aspect-build/rules_jasmine#166]
### What happened?

ERROR: tools/node/BUILD:8:15: //tools/node:tests: no such attribute 'unresolved_symlinks_enabled' in 'jasmine_test' rule

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

**Comment by jbedard** [comment]
2.0.0 has been tagged and will be on the BCR soon
