### ISSUE TITLE
migrate tests from rules_nodejs

### ISSUE THREAD

**Issue by thesayyn** [aspect-build/rules_jasmine#8]
There are some tests in rules_nodejs that would give good test coverage and regressions we introduce with the new ruleset. 

https://github.com/bazelbuild/rules_nodejs/tree/stable/packages/jasmine/test

**Comment by alexeagle** [comment]
Jason since we are deleting from rules_nodejs this is a good reminder that some of the files from packages/jasmine need to come over here.
